version: '3.7'

services:
  grafana:
    image: grafana/grafana:9.5.5
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
  go-app:
    build:
      context: ./go-app
      dockerfile: ./Dockerfile
    container_name: go-app
    restart: always
    ports:
      - '9000:9000'
  prometheus:
    image: prom/prometheus:v2.40.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

volumes:
  grafana-storage:
  prometheus_data: