apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadvisor
  namespace: default
  labels:
    app: cadvisor
spec:
  selector:
    matchLabels:
      app: cadvisor
  replicas: 1
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      containers:
      - name: cadvisor
        image: gcr.io/cadvisor/cadvisor:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 8080
          name: cadvisor
          # volumes in docker compose:
          # - /:/rootfs:ro
          # - /var/run:/var/run:rw
          # - /sys:/sys:ro
          # - /var/lib/docker/:/var/lib/docker:ro
        volumeMounts:
        - name: root
          mountPath: /rootfs
          readOnly: true
        - name: run
          mountPath: /var/run
          readOnly: false
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: docker
          mountPath: /var/lib/docker
          readOnly: true
      volumes:
      - name: root
        hostPath:
          path: /
      - name: run
        hostPath:
          path: /var/run
      - name: sys
        hostPath:
          path: /sys
      - name: docker
        hostPath:
          path: /var/lib/docker
      restartPolicy: Always
