apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: default
spec:
  selector:
    app: cadvisor
  type: ClusterIP
  ports:
  - name: cadvisor-port
    protocol: TCP
    port: 8081
    targetPort: 8080
