apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: default
  labels:
    app: go-app
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 1
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: go-app:latest
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 200Mi
        livenessProbe:
          httpGet:
            path: /live
            port: 9000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 9000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        ports:
        - containerPort: 9000
          name: go-app-port
      restartPolicy: Always
