apiVersion: v1
kind: Service
metadata:
  name: go-app
  namespace: default
spec:
  selector:
    app: go-app
  type: ClusterIP
  ports:
  - name: go-app-port
    protocol: TCP
    port: 9000
    targetPort: 9000
