apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: default
spec:
  selector:
    app: grafana
  type: ClusterIP
  ports:
  - name: grafana-port
    protocol: TCP
    port: 3000
    targetPort: 3000
