apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: default
spec:
  selector:
    matchLabels:
      app: prometheus # has to match .spec.template.metadata.labels
  serviceName: "prometheus"
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: prometheus
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus
        - --web.console.libraries=/usr/share/prometheus/console_libraries
        - --web.console.templates=/usr/share/prometheus/consoles
        image: prometheus:v2.45.0
        #  prometheus:{{ .Values.prometheus_version | quote }}
        ports:
        - containerPort: 9090
          name: web
        volumeMounts:
        - name: prometheuspv
          mountPath: /prometheus
        - name: prometheusconfig
          mountPath: /etc/prometheus
  volumeClaimTemplates:
  - metadata:
      name: prometheuspv
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: prometheusconfig
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Mi
