{
 "title": "my dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "go-app memory usage (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"go-app\"} / 1048576"
    }
   ]
  },
  {
   "title": "go-app requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "go-app cpu",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cpu) (rate(container_cpu_usage_seconds_total{name=\"go-app\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "go-app/ responce time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_response_time_seconds_count{path=\"/\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "non-OK responces rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(response_status{status!=\"200\"}[$__rate_interval])"
    }
   ]
  }
 ]
}