apiVersion: 1

# list of datasources that should be deleted from the database
# deleteDatasources:
# - name: Prometheus
#   orgId: 1

datasources:
- name: Prometheus-1
  orgId: 1
  type: prometheus
  # Access mode - proxy (server in the UI) or direct (browser in the UI).
  access: proxy
  url: http://simple-monitoring-prometheus-1:9090
  jsonData:
  httpMethod: POST
  manageAlerts: true
  prometheusType: Prometheus
  # TODO: create env variable
  prometheusVersion: ${PROMETHEUS_VERSION}
  cacheLevel: 'High'
  incrementalQuerying: true
  incrementalQueryOverlapWindow: 10m
  exemplarTraceIdDestinations:
  - datasourceUid: my_prometheus_uid
